export const CHANGE_ROUTE = 'CHANGE_ROUTE';
export const FETCH_NEW_STREAM_SONGS_SUCCESS = 'FETCH_NEW_STREAM_SONGS_SUCCESS';
export const FETCH_NEW_STREAM_SONGS_FAIL = 'FETCH_NEW_STREAM_SONGS_FAIL';
export const FETCH_SESSION_LIKES_SUCCESS = 'FETCH_SESSION_LIKES_SUCCESS';
export const FETCH_SESSION_FOLLOWINGS_SUCCESS = 'FETCH_SESSION_FOLLOWINGS_SUCCESS';
export const FETCH_SESSION_PLAYLISTS_SUCCESS = 'FETCH_SESSION_PLAYLISTS_SUCCESS';
export const FETCH_SESSION_USER_SUCCESS = 'FETCH_SESSION_USER_SUCCESS';
export const FETCH_SONG_COMMENTS_SUCCESS = 'FETCH_SONG_COMMENTS_SUCCESS';
export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_USER_FOLLOWINGS_SUCCESS = 'FETCH_USER_FOLLOWINGS_SUCCESS';
export const FETCH_USER_PROFILES_SUCCESS = 'FETCH_USER_PROFILES_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const LOAD_NEW_STREAM_SONGS = 'LOAD_NEW_STREAM_SONGS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const ON_LOAD_START = 'ON_LOAD_START';
export const ON_LOADED_METADATA = 'ON_LOADED_METADATA';
export const ON_PAUSE = 'ON_PAUSE';
export const ON_PLAY = 'ON_PLAY';
export const ON_TIME_UPDATE = 'ON_TIME_UPDATE';
export const ON_VOLUME_CHANGE = 'ON_VOLUME_CHANGE';
export const PLAY_SONG = 'PLAY_SONG';
export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const TOGGLE_SHOW_HISTORY = 'TOGGLE_SHOW_HISTORY';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const WINDOW_RESIZE = 'WINDOW_RESIZE';

/**
 * songs header filter actions
 */
export const CHANGE_GENRE = 'CHANGE_GENRE';
export const CHANGE_TIME = 'CHANGE_TIME';

/* 
 * fetch track actions
*/

export const FETCH_TRACK_SUCESS = 'FETCH_TRACK_SUCESS';
export const FETCH_TRACK_FAILURE = 'FETCH_TRACK_FAILURE';
export const FETCH_TRACKS_SUCESS = 'FETCH_TRACKS_SUCESS';
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE';
export const FETCH_TRACK_SUBRESOURCE_SUCESS = 'FETCH_TRACK_SUBRESOURCE_SUCESS';
export const FETCH_TRACK_SUBRESOURCE_FAILURE = 'FETCH_TRACK_SUBRESOURCE_FAILURE';

/**
 * player actions
 */
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPDATE_DURATION = 'CHANGE_DURATION';
export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';
export const UPDATE_ISPLAYED = "UPDATE_IS_PLAYED";
export const UPDATE_CAN_PLAYED = "UPDATE_CAN_PLAYED";
export const PAUSE = "PAUSE";
export const PLAY = "PLAY";
export const TOGGLE_PLAY = "TOGGLE_PLAY";
export const UPDATE_VOLUME = 'UPDATE_VOLUME';
export const UPDATE_CURRENT_TRACK = "UPDATE_CURRENT_TRACK";
export const CURRENT_TIME_JUMP_TO = "CURRENT_TIME_JUMP_TO";